### ISSUE TITLE
No device found!

### ISSUE THREAD

**Issue by sandip1604** [sevensense-robotics/alphasense_core_manual#13]
I am trying to setup the alphasense on my laptop but on running `alphasense list` I am getting no device found error

![Screenshot from 2022-04-08 11-36-50](https://user-images.githubusercontent.com/60662785/162475468-e3fee7f2-ac26-4bc0-aae6-eb26112bebec.png)

Here is the setting I have done to my networking based on the core manual on this github:

![image](https://user-images.githubusercontent.com/60662785/162475651-59c38938-0977-4f4d-b8e6-b16ba41e65b9.png)

**Comment by dymczykm** [comment]
Dear Sandip, thanks a lot for describing your issue precisely. I believe you got in touch with our support team and got assistance there. I will close the issue now, don't hesitate to contact us in the future. Best regards
